$axure.loadCurrentPage({
  "url":"页面_2.html",
  "generationDate":new Date(1467131121062.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a0c4c239b09d413ea64783b8ee8ceedf",
    "type":"Axure:Page",
    "name":"页面 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6d75e1a550c94611aa95caf02d671c24",
          "label":"项目1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":599}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5b8c13a24de441ea9214c22ff406b49e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"bd2ed67b3c3c448296d654d784ae0d54",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":105},
            "size":{
              "width":617,
              "height":495}},
          "adaptiveStyles":{
}},
{
          "id":"41dbdafb181047fd9019a8d52bbe1b69",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":105},
            "size":{
              "width":183,
              "height":495}},
          "adaptiveStyles":{
}},
{
          "id":"50ea9f2e75ef4f63a7368c03b612b797",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":78},
            "size":{
              "width":137,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"aa3cae11da374a87a8fca9e2e8ba5719",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":337,
              "y":78},
            "size":{
              "width":47,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"47abbeaeb27241a79569033439e198f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":883,
              "y":78},
            "size":{
              "width":117,
              "height":27},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9cc39cfe789482b94265e0ff05d4b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":883,
                  "y":78},
                "size":{
                  "width":117,
                  "height":27},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u5.png"}},
{
          "id":"e66d152dd17f46ce9ac6f5e51381ac58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":78},
            "size":{
              "width":167,
              "height":27},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332dcd4308934a4d805f39024292315b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":78},
                "size":{
                  "width":167,
                  "height":27},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u7.png"}},
{
          "id":"e283d0419d52497bbcd19d5a352d7d90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":78},
            "size":{
              "width":167,
              "height":27},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45254f6345ec4e50b668e707263cfec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":78},
                "size":{
                  "width":167,
                  "height":27},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u7.png"}},
{
          "id":"ff790dcee407443faaf1d9395f0b2f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":78},
            "size":{
              "width":167,
              "height":27},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2a79f2b702d4046a3e9d8d91bc0bb8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":383,
                  "y":78},
                "size":{
                  "width":167,
                  "height":27},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 A水库详情,<br>(表格)",
                      "objectsToFades":[{
                          "objectPath":["85ce7d2afe6e49f7b8cc067ca8d6b0ec"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8e01deeecea64e2dba6e7f02d82cb164"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/页面_2/u7.png"}},
{
          "id":"24757ff707064b808e4aa89490e763de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":550,
              "y":19},
            "size":{
              "width":60,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73c5e6c11acf4610bad585340668f9fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":550,
                  "y":19},
                "size":{
                  "width":60,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u13.png"}},
{
          "id":"d58c71b89984463da5c59502eea51658",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":627,
              "y":19},
            "size":{
              "width":57,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec305b612bd54239b0477f18105bcd94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":627,
                  "y":19},
                "size":{
                  "width":57,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u15.png"}},
{
          "id":"0beed04a01324be59d9c14486d2d3911",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":700,
              "y":31},
            "size":{
              "width":83,
              "height":24},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d153e75f559429e9b899ad6390e65d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":700,
                  "y":31},
                "size":{
                  "width":83,
                  "height":24},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u17.png"}},
{
          "id":"ea625985a3b64e75984322dacaa6bb03",
          "label":"水库总表",
          "type":"table",
          "styleType":"table",
          "visible":false,
          "style":{
            "location":{
              "x":200,
              "y":105},
            "size":{
              "width":183,
              "height":54},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cb45bb82d434b539cd407e5c2cb46e0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":19},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bb0606a1fc54b8d8a9f970d882f449c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":19},
                    "size":{
                      "width":66,
                      "height":15}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u24.png"}},
{
              "id":"962eea1395824ebca85800a6a7d7ab8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a1b7e6e85cc4edf881eb65eb42ffa02",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":66,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u28.png"}},
{
              "id":"a4951ff81454486da4dcedfbdbc2242c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":19},
                "size":{
                  "width":117,
                  "height":15}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73bbf2b1e6ab42bab1ccfebcd3cc190e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":66,
                      "y":19},
                    "size":{
                      "width":117,
                      "height":15}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u26.png"}},
{
              "id":"0929cdc4db514092b4b7c28269371e05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":34},
                "size":{
                  "width":117,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"691a8129c7594996ad9ae166d0b96c39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":66,
                      "y":34},
                    "size":{
                      "width":117,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u30.png"}},
{
              "id":"6a3730e02a36403894f96d8fd4776ee6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":66,
                  "height":19}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73631f212b1b4ebf9f865e9cecb63b11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":66,
                      "height":19}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u20.png"}},
{
              "id":"3dfae3817d0b4b18985c886a399b7e75",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":0},
                "size":{
                  "width":117,
                  "height":19}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8fcee4d6ba1a441cb1e177d0f7790b41",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":66,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":19}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u22.png"}}]},
{
          "id":"c49e25cf0e3841e6a38720ed182a7e6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":103},
            "size":{
              "width":97,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dee27233c5e4b65a8532a3dd5f18fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":103},
                "size":{
                  "width":97,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u32.png"}},
{
          "id":"6857459f44d54b1ea1a38ed7a9877797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":65,
              "y":161},
            "size":{
              "width":21,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebb4ed8fbccc4fadb3d3cf2af548f4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":65,
                  "y":161},
                "size":{
                  "width":21,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81b337cb5e8246499d2e99f46f5b6dc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":192},
            "size":{
              "width":78,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af84575d9c2648408bf7a540adbf1161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":192},
                "size":{
                  "width":78,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_2/u36.png"}},
{
          "id":"84d7e88aee734a9cb8480868108b2876",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":65,
              "y":270},
            "size":{
              "width":21,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c3a6bdc2d324f6bb7f8e27b40ac3888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":65,
                  "y":270},
                "size":{
                  "width":21,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4204d1f83f3d4c17b683ab936b485d47",
          "label":"水井总表",
          "type":"table",
          "styleType":"table",
          "visible":false,
          "style":{
            "location":{
              "x":200,
              "y":105},
            "size":{
              "width":184,
              "height":54},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686e937c39c049688261d23f5665c1a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":19},
                "size":{
                  "width":66,
                  "height":14}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f462c7ed73094396957858514df1264c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":19},
                    "size":{
                      "width":66,
                      "height":14}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u45.png"}},
{
              "id":"e271f4979b4144929ca3e5ea153b9f8c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":66,
                  "height":21}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04de108205074c3299943fd0dad737df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":66,
                      "height":21}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u49.png"}},
{
              "id":"e41f4b0783864e0bb41efdc5e5216ebb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":19},
                "size":{
                  "width":118,
                  "height":14}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5303800dd5b6494489d2addd36bb9673",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":66,
                      "y":19},
                    "size":{
                      "width":118,
                      "height":14}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u47.png"}},
{
              "id":"482c1e5606c7478b85c54e271adcc969",
              "label":"水井总表",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":33},
                "size":{
                  "width":118,
                  "height":21}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"51aa030045d0415692ade997b949ed07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":66,
                      "y":33},
                    "size":{
                      "width":118,
                      "height":21}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/水井总表_u51.png"}},
{
              "id":"60b42b741f534b34a24034492cc030ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":66,
                  "height":19}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b91761a00eab43d7a841c6a2eb6f46a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":66,
                      "height":19}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u20.png"}},
{
              "id":"3fca32dd46364ce2827dc636a4acba8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":0},
                "size":{
                  "width":118,
                  "height":19}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82188dfdccb24f1e8678129cbdcde2d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"8px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":66,
                      "y":0},
                    "size":{
                      "width":118,
                      "height":19}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u43.png"}}]},
{
          "id":"2b821fc96ef049e8935f0856cb5595c0",
          "label":"水库热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":114},
            "size":{
              "width":83,
              "height":75}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 水库总表 淡入淡出 500 ms 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["ea625985a3b64e75984322dacaa6bb03"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"front"}}}]}]}]}},
          "tabbable":true},
{
          "id":"07edca17356446c88b8487530f06864c",
          "label":"水井热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":204},
            "size":{
              "width":82,
              "height":96}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 水井总表 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["4204d1f83f3d4c17b683ab936b485d47"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"front"}}}]}]}]}},
          "tabbable":true},
{
          "id":"8e01deeecea64e2dba6e7f02d82cb164",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":false,
          "style":{
            "location":{
              "x":383,
              "y":159},
            "size":{
              "width":617,
              "height":91},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdbd08edba1e4474b89f374002fca0ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71406bd932e2481e9186c61fce36c755",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u56.png"}},
{
              "id":"a8e5d92480e9476ab6df21ba9b575b36",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2c37c6b37d74c7da620644723fe8796",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u56.png"}},
{
              "id":"8c210f0988b34b1081df1cb8a0ebed30",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":202,
                  "height":31}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ba8421c8348470a92fd6b08a9bffeed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":202,
                      "height":31}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u68.png"}},
{
              "id":"d2c38acd14e04b31b6d202b37bca60e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":0},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8bc433fe2074886bcad08ceb44e3eae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":0},
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u56.png"}},
{
              "id":"5536d5d8ccfe4daf9a8e398364fb3a6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":30},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0991c50ca76a4564b7a44c8cf877cf79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":30},
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u56.png"}},
{
              "id":"c3f367fe982149b5be683ea669a5f0b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":60},
                "size":{
                  "width":202,
                  "height":31}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1faa38cefc44b97875b72e81a349830",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":60},
                    "size":{
                      "width":202,
                      "height":31}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u68.png"}},
{
              "id":"75a9f427f7dd4423b7b2db75914c119b",
              "label":"A水库详情",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":404,
                  "y":0},
                "size":{
                  "width":213,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a864ae1e48c41a0bc1c78d47ff079b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":404,
                      "y":0},
                    "size":{
                      "width":213,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/a水库详情_u60.png"}},
{
              "id":"5265f6eeec984499b65cfb47fb69101a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":404,
                  "y":30},
                "size":{
                  "width":213,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9aa190d05e864189a147eb50c0415f6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":404,
                      "y":30},
                    "size":{
                      "width":213,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/a水库详情_u60.png"}},
{
              "id":"4e7c1ca488e147c0b7d0356eca28fde5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":404,
                  "y":60},
                "size":{
                  "width":213,
                  "height":31}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dc4954eb65d4c5dade77c7812bea8d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":404,
                      "y":60},
                    "size":{
                      "width":213,
                      "height":31}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/页面_2/u72.png"}}]},
{
          "id":"85ce7d2afe6e49f7b8cc067ca8d6b0ec",
          "label":"A水库详情",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":383,
              "y":105},
            "size":{
              "width":617,
              "height":55},
            "visible":false},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "6d75e1a550c94611aa95caf02d671c24":{
      "scriptId":"u0"},
    "bd2ed67b3c3c448296d654d784ae0d54":{
      "scriptId":"u1"},
    "41dbdafb181047fd9019a8d52bbe1b69":{
      "scriptId":"u2"},
    "50ea9f2e75ef4f63a7368c03b612b797":{
      "scriptId":"u3"},
    "aa3cae11da374a87a8fca9e2e8ba5719":{
      "scriptId":"u4"},
    "47abbeaeb27241a79569033439e198f9":{
      "scriptId":"u5"},
    "f9cc39cfe789482b94265e0ff05d4b90":{
      "scriptId":"u6"},
    "e66d152dd17f46ce9ac6f5e51381ac58":{
      "scriptId":"u7"},
    "332dcd4308934a4d805f39024292315b":{
      "scriptId":"u8"},
    "e283d0419d52497bbcd19d5a352d7d90":{
      "scriptId":"u9"},
    "45254f6345ec4e50b668e707263cfec6":{
      "scriptId":"u10"},
    "ff790dcee407443faaf1d9395f0b2f50":{
      "scriptId":"u11"},
    "b2a79f2b702d4046a3e9d8d91bc0bb8c":{
      "scriptId":"u12"},
    "24757ff707064b808e4aa89490e763de":{
      "scriptId":"u13"},
    "73c5e6c11acf4610bad585340668f9fd":{
      "scriptId":"u14"},
    "d58c71b89984463da5c59502eea51658":{
      "scriptId":"u15"},
    "ec305b612bd54239b0477f18105bcd94":{
      "scriptId":"u16"},
    "0beed04a01324be59d9c14486d2d3911":{
      "scriptId":"u17"},
    "0d153e75f559429e9b899ad6390e65d9":{
      "scriptId":"u18"},
    "ea625985a3b64e75984322dacaa6bb03":{
      "scriptId":"u19"},
    "6a3730e02a36403894f96d8fd4776ee6":{
      "scriptId":"u20"},
    "73631f212b1b4ebf9f865e9cecb63b11":{
      "scriptId":"u21"},
    "3dfae3817d0b4b18985c886a399b7e75":{
      "scriptId":"u22"},
    "8fcee4d6ba1a441cb1e177d0f7790b41":{
      "scriptId":"u23"},
    "1cb45bb82d434b539cd407e5c2cb46e0":{
      "scriptId":"u24"},
    "5bb0606a1fc54b8d8a9f970d882f449c":{
      "scriptId":"u25"},
    "a4951ff81454486da4dcedfbdbc2242c":{
      "scriptId":"u26"},
    "73bbf2b1e6ab42bab1ccfebcd3cc190e":{
      "scriptId":"u27"},
    "962eea1395824ebca85800a6a7d7ab8d":{
      "scriptId":"u28"},
    "8a1b7e6e85cc4edf881eb65eb42ffa02":{
      "scriptId":"u29"},
    "0929cdc4db514092b4b7c28269371e05":{
      "scriptId":"u30"},
    "691a8129c7594996ad9ae166d0b96c39":{
      "scriptId":"u31"},
    "c49e25cf0e3841e6a38720ed182a7e6b":{
      "scriptId":"u32"},
    "4dee27233c5e4b65a8532a3dd5f18fc4":{
      "scriptId":"u33"},
    "6857459f44d54b1ea1a38ed7a9877797":{
      "scriptId":"u34"},
    "ebb4ed8fbccc4fadb3d3cf2af548f4c4":{
      "scriptId":"u35"},
    "81b337cb5e8246499d2e99f46f5b6dc4":{
      "scriptId":"u36"},
    "af84575d9c2648408bf7a540adbf1161":{
      "scriptId":"u37"},
    "84d7e88aee734a9cb8480868108b2876":{
      "scriptId":"u38"},
    "6c3a6bdc2d324f6bb7f8e27b40ac3888":{
      "scriptId":"u39"},
    "4204d1f83f3d4c17b683ab936b485d47":{
      "scriptId":"u40"},
    "60b42b741f534b34a24034492cc030ba":{
      "scriptId":"u41"},
    "b91761a00eab43d7a841c6a2eb6f46a0":{
      "scriptId":"u42"},
    "3fca32dd46364ce2827dc636a4acba8a":{
      "scriptId":"u43"},
    "82188dfdccb24f1e8678129cbdcde2d8":{
      "scriptId":"u44"},
    "686e937c39c049688261d23f5665c1a2":{
      "scriptId":"u45"},
    "f462c7ed73094396957858514df1264c":{
      "scriptId":"u46"},
    "e41f4b0783864e0bb41efdc5e5216ebb":{
      "scriptId":"u47"},
    "5303800dd5b6494489d2addd36bb9673":{
      "scriptId":"u48"},
    "e271f4979b4144929ca3e5ea153b9f8c":{
      "scriptId":"u49"},
    "04de108205074c3299943fd0dad737df":{
      "scriptId":"u50"},
    "482c1e5606c7478b85c54e271adcc969":{
      "scriptId":"u51"},
    "51aa030045d0415692ade997b949ed07":{
      "scriptId":"u52"},
    "2b821fc96ef049e8935f0856cb5595c0":{
      "scriptId":"u53"},
    "07edca17356446c88b8487530f06864c":{
      "scriptId":"u54"},
    "8e01deeecea64e2dba6e7f02d82cb164":{
      "scriptId":"u55"},
    "cdbd08edba1e4474b89f374002fca0ef":{
      "scriptId":"u56"},
    "71406bd932e2481e9186c61fce36c755":{
      "scriptId":"u57"},
    "d2c38acd14e04b31b6d202b37bca60e4":{
      "scriptId":"u58"},
    "e8bc433fe2074886bcad08ceb44e3eae":{
      "scriptId":"u59"},
    "75a9f427f7dd4423b7b2db75914c119b":{
      "scriptId":"u60"},
    "3a864ae1e48c41a0bc1c78d47ff079b4":{
      "scriptId":"u61"},
    "a8e5d92480e9476ab6df21ba9b575b36":{
      "scriptId":"u62"},
    "c2c37c6b37d74c7da620644723fe8796":{
      "scriptId":"u63"},
    "5536d5d8ccfe4daf9a8e398364fb3a6b":{
      "scriptId":"u64"},
    "0991c50ca76a4564b7a44c8cf877cf79":{
      "scriptId":"u65"},
    "5265f6eeec984499b65cfb47fb69101a":{
      "scriptId":"u66"},
    "9aa190d05e864189a147eb50c0415f6b":{
      "scriptId":"u67"},
    "8c210f0988b34b1081df1cb8a0ebed30":{
      "scriptId":"u68"},
    "1ba8421c8348470a92fd6b08a9bffeed":{
      "scriptId":"u69"},
    "c3f367fe982149b5be683ea669a5f0b7":{
      "scriptId":"u70"},
    "e1faa38cefc44b97875b72e81a349830":{
      "scriptId":"u71"},
    "4e7c1ca488e147c0b7d0356eca28fde5":{
      "scriptId":"u72"},
    "6dc4954eb65d4c5dade77c7812bea8d9":{
      "scriptId":"u73"},
    "85ce7d2afe6e49f7b8cc067ca8d6b0ec":{
      "scriptId":"u74"}}});